CREATE TABLE RESIDENTS_BOARD(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    MEMBER_ID VARCHAR(255) NOT NULL FOREIGN KEY, -- 멤버 아이디
    MEMBER_NAME VARCHAR(255) NOT NULL, -- 멤버 이름
    MEMBER_REPORTED_COUNT INTEGER NOT NULL, -- 신고 당한 횟수
    MEMBER_REPORTS INTEGER NOT NULL, -- 신고한 횟수
    MEMBER_LIKES INTEGER NOT NULL, -- 좋아요 누른 횟수
    MEMBER_LIKED_COUNT INTEGER NOT NULL, -- 좋아요 당한 횟수
    MEMBER_CONTENTS VARCHAR(5000) NOT NULL, -- 멤버가 등록한 글 내용
    MEMBER_COMMENTS VARCHAR(5000) NOT NULL, -- 멤버가 등록한 댓글
);


