-- 여기에는 TABLE 들 작성
-- 아래는 임시 입니다.
CREATE TABLE IF NOT EXISTS ADMIN (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ADMIN_ID VARCHAR(255) NOT NULL,
    ADMIN_PW VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USER_ID VARCHAR(255) NOT NULL,
    USER_PW VARCHAR(255) NOT NULL
);